### ISSUE TITLE
css brocken in Firefox using the latest charts.css CDN

### ISSUE THREAD

**Issue by ratmole** [christian-fei/minimal-analytics#8]
After the 2 latest charts.css updates the css is all over the place.
using charts.css@1.1.0 and charts.css@1.0.1 with Firefox the stat bars are not shown properly aligned. 
In Chrome everything is ok.

charts.css@1.0.0 is ok for both of them.
using 

`  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/charts.css@1.0.0/dist/charts.min.css">`

in the dashboard/index.html, fixes the issue.

thanks

**Comment by christian-fei** [comment]
thanks so much! and sorry for the extremely late reply, must have missed this notification :/
